"""Add applications table

Revision ID: 2b0300107c51
Revises: e508b906922b
Create Date: 2026-08-26 14:41:47.974833
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b0300107c51'
down_revision: Union[str, None] = 'e508b906922b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('DETECTED', 'SUMMARY_READY', 'WAITING_FOR_PREPARATION_APPROVAL', 'PREPARING', 'QUESTIONS_PENDING', 'VALIDATING', 'READY_FOR_REVIEW', 'WAITING_FOR_SUBMISSION_APPROVAL', 'SUBMITTING', 'SUBMITTED', 'FAILED', 'MANUAL_ACTION_REQUIRED', name='application_state'), nullable=False),
    sa.Column('preparation_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###