"""Add opportunities table

Revision ID: e508b906922b
Revises: 50ace852b7c7
Create Date: 2026-08-26 12:36:31.378781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e508b906922b'
down_revision: Union[str, None] = '50ace852b7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('technical', sa.Boolean(), nullable=True),
    sa.Column('package', sa.String(length=100), nullable=True),
    sa.Column('apply_url', sa.String(length=1000), nullable=True),
    sa.Column('bond', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligible_branches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('eligible_graduation_year', sa.Integer(), nullable=True),
    sa.Column('active_backlogs_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_message_id'), 'opportunities', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_message_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###